import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { CookiesProvider } from "next-client-cookies/server";
import Navigation from "@/components/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "%s • AniWatch",
    default: "AniWatch",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <CookiesProvider>
        <html lang="en">
          <body className={`${inter.className} bg-zinc-900 text-white`}>
            <Navigation />
            {children}
          </body>
        </html>
      </CookiesProvider>
    </Providers>
  );
}
