import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { CookiesProvider } from "next-client-cookies/server";
import Navigation from "@/components/navigation";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "%s • AniWatch",
    default: "AniWatch",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CookiesProvider>
      <html lang="en">
        <body className={`${manrope.className} bg-zinc-900 text-white`}>
          <main className="max-w-3xl mx-auto">
            <Providers>
              <Navigation />
              {children}
            </Providers>
          </main>
        </body>
      </html>
    </CookiesProvider>
  );
}
